/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crud;

/**
 *
 * @author polip
 */
public class Ingreso_Factura extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_Factura
     */
    public Ingreso_Factura() {
        initComponents();
        db=new ConexionOracle("25.66.186.128","cdb1","achafla","achafla");
        CBCedula.setModel(db.Listado("Cliente", "cli_cedula_ruc"));
        CBSucursal.setModel(db.Listado("Sucursal", "suc_nombre"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBCedula = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        CBSucursal = new javax.swing.JComboBox<>();
        CBCat = new javax.swing.JComboBox<>();
        CBProductos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ingresar Nuevo CLiente");

        CBSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSucursalActionPerformed(evt);
            }
        });

        CBCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCatActionPerformed(evt);
            }
        });

        CBProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(CBProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBSucursal, 0, 139, Short.MAX_VALUE)
                            .addComponent(CBCedula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(CBSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(369, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSucursalActionPerformed
        // TODO add your handling code here:
        String Sucursal=CBSucursal.getSelectedItem().toString();
        IDSucursal=db.get("SELECT SUC_CODIGO FROM SUCURSAL WHERE SUC_NOMBRE='"+Sucursal+"'");
        System.out.println(IDSucursal);
        String Comando="SELECT C.CAT_DESCRIPCION " +
        "FROM PRODUCTO P " +
        "INNER JOIN PRODUCTO_BODEGA PB " +
        "ON P.PRD_CODIGO=PB.PRD_CODIGO " +
        "INNER JOIN BODEGA B " +
        "ON B.BOD_CODIGO=PB.BOD_CODIGO " +
        "INNER JOIN SUCURSAL S " +
        "ON S.SUC_CODIGO=B.SUC_CODIGO " +
         "INNER JOIN CATEGORIA C ON C.CAT_CODIGO=P.CAT_CODIGO "+
        "WHERE S.SUC_CODIGO='"+IDSucursal+"' " +
        "GROUP BY C.CAT_DESCRIPCION " +
        "ORDER BY C.CAT_DESCRIPCION";
        System.out.println(Comando);
        CBCat.setModel(db.ListadoComplejo(Comando));
    }//GEN-LAST:event_CBSucursalActionPerformed

    private void CBProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBProductosActionPerformed
        // TODO add your handling code here:
        String Producto=CBProductos.getSelectedItem().toString();
        IDProducto=db.get("SELECT PRD_CODIGO FROM PRODUCTO WHERE PRD_DESCRIPCION='"+Producto+"'");
    }//GEN-LAST:event_CBProductosActionPerformed

    private void CBCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCatActionPerformed
        // TODO add your handling code here:
        String Categoria=CBCat.getSelectedItem().toString();
        IDCategoria=db.get("SELECT CAT_CODIGO FROM CATEGORIA WHERE CAT_DESCRIPCION='"+Categoria+"'");
        String Comando="SELECT P.PRD_DESCRIPCION " +
        "FROM PRODUCTO P " +
        "INNER JOIN PRODUCTO_BODEGA PB " +
        "ON P.PRD_CODIGO=PB.PRD_CODIGO " +
        "INNER JOIN BODEGA B " +
        "ON B.BOD_CODIGO=PB.BOD_CODIGO " +
        "INNER JOIN SUCURSAL S " +
        "ON S.SUC_CODIGO=B.SUC_CODIGO " +
        "WHERE S.SUC_CODIGO='"+IDSucursal+"' " +
        "AND P.CAT_CODIGO='"+IDCategoria+"' " +
        "GROUP BY P.PRD_DESCRIPCION";
        CBProductos.setModel(db.ListadoComplejo(Comando));
    }//GEN-LAST:event_CBCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCat;
    private javax.swing.JComboBox<String> CBCedula;
    private javax.swing.JComboBox<String> CBProductos;
    private javax.swing.JComboBox<String> CBSucursal;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    private ConexionOracle db;
    private String IDSucursal;
    private String IDCategoria;
    private String IDProducto;
}
